services:
  ml-api-service:
    image: ml-api-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_CONFIG_PATH=src/serve/config.yaml
      - FASTAPI_PORT=${FASTAPI_PORT}
    ports:
      - "5050:${FASTAPI_PORT}"
