# config.yaml
output_dir: artifacts
model_version: 1.3.0    # bump whenever pipeline changes
sepal_bins: 3           # expose KBinsDiscretizer choice
petal_scaler_range: [0.0, 1.0]
logreg_max_iter: 300
